### ISSUE TITLE
请问一下这个是需要账号购买订阅使用的吗

### ISSUE THREAD

**Issue by ElainaFanBoy** [Ikaros-521/nonebot_plugin_midjourney#1]

**Comment by Ikaros-521** [comment]
是的，需要账号本身拥有使用权限，新账号有一定的免费额度，但其实不多，可以搞很多新号，不过有点麻烦，实际额度也很少。
还是付费账号才能比较好的使用

**Comment by ElainaFanBoy** [comment]
了解了，辛苦

**Comment by Ikaros-521** [comment]
确实是个很麻烦的点，门槛高了不少，不知道网上有没有共享账号可以用

**Comment by ElainaFanBoy** [comment]
> 确实是个很麻烦的点，门槛高了不少，不知道网上有没有共享账号可以用

如果合租的话会不会被ban，标准版一个月30刀有点难顶
